version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-redux
    versions:
    - 7.1.0
    - 7.2.2
    - 7.2.3
  - dependency-name: react
    versions:
    - 16.14.0
    - 17.0.1
  - dependency-name: redux
    versions:
    - 4.0.5
  - dependency-name: react-icons
    versions:
    - 4.1.0
  - dependency-name: react-scripts
    versions:
    - 4.0.1
